// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// DO NOT add repositories here - they are defined in settings.gradle
// DO NOT add allprojects { repositories {} } - violates RepositoriesMode.FAIL_ON_PROJECT_REPOS

task clean(type: Delete) {
    delete rootProject.buildDir
}
